# Generated by Django 3.2.2 on 2021-05-12 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('proteinas', models.CharField(max_length=80)),
                ('acompanhamentos', models.CharField(max_length=100)),
                ('saldas', models.CharField(max_length=70)),
                ('quantidade', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.IntegerField()),
                ('endereco', models.CharField(max_length=80)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
    ]
