# Generated by Django 3.2.2 on 2021-05-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
    ]
