# Generated by Django 3.2.2 on 2021-05-12 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_alter_pedido_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='saldas',
            new_name='saladas',
        ),
    ]
