# Generated by Django 3.2.2 on 2021-05-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_rename_saldas_pedido_saladas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
