# Generated by Django 3.2.2 on 2021-05-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0004_alter_pedido_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='valor',
            field=models.CharField(max_length=20),
        ),
    ]
