# Generated by Django 3.2.2 on 2021-05-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0005_alter_pedido_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='saladas',
            field=models.CharField(max_length=80),
        ),
    ]
