# Generated by Django 3.2.2 on 2021-05-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0006_alter_pedido_saladas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='quantidade',
            field=models.CharField(max_length=20),
        ),
    ]
