# Generated by Django 3.2.2 on 2021-05-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0007_alter_pedido_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
