# Generated by Django 3.2.2 on 2021-05-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0008_alter_pedido_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
