# Generated by Django 3.2.2 on 2021-05-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0009_alter_pedido_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
