# Generated by Django 3.2.2 on 2021-05-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0013_pedido_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
    ]
