# Generated by Django 3.2.2 on 2021-05-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0014_remove_pedido_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='valor',
            field=models.FloatField(),
        ),
    ]
